apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongodb-root-username: dGhpc2lzdGhldXNlcmZvciB0aGVkYXRhYmFzZQ==
  mongodb-root-password: dGhpcyBpcyB0aGUgYmVzdCBwYXNzd2QgaSBnb3Q=